from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Klass(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nimi = db.Column(db.String(20), nullable=False)
    saving_throw = db.Column(db.Text, nullable=False)
    text = db.Column(db.Text, nullable=False)
    hit_points=db.Column(db.String(4), nullable=True)
    proficiencies=db.Column(db.Text, nullable=True)
    equipment=db.Column(db.Text, nullable=True)
    features=db.Column(db.Text, nullable=True)
    lvl1=db.Column(db.Text, nullable=True)
    lvl2 = db.Column(db.Text, nullable=True)
    lvl3 = db.Column(db.Text, nullable=True)
    lvl4 = db.Column(db.Text, nullable=True)
    lvl5 = db.Column(db.Text, nullable=True)
    lvl6 = db.Column(db.Text, nullable=True)
    lvl7 = db.Column(db.Text, nullable=True)
    lvl8 = db.Column(db.Text, nullable=True)
    lvl9 = db.Column(db.Text, nullable=True)
    lvl10 = db.Column(db.Text, nullable=True)
    lvl11 = db.Column(db.Text, nullable=True)
    lvl12 = db.Column(db.Text, nullable=True)
    lvl13 = db.Column(db.Text, nullable=True)
    lvl14 = db.Column(db.Text, nullable=True)
    lvl15 = db.Column(db.Text, nullable=True)
    lvl16 = db.Column(db.Text, nullable=True)
    lvl17 = db.Column(db.Text, nullable=True)
    lvl18 = db.Column(db.Text, nullable=True)
    lvl19 = db.Column(db.Text, nullable=True)
    lvl20 = db.Column(db.Text, nullable=True)
    small_text= db.Column(db.String(60), nullable=True)
    homebrew_id=db.Column(db.Integer, nullable=True)

class Rass(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nimi = db.Column(db.String(20), nullable=False)
    ability_score_increase = db.Column(db.Text, nullable=False)
    text = db.Column(db.Text, nullable=False)
    speed=db.Column(db.Text, nullable=True)
    size=db.Column(db.Text, nullable=True)
    race_feats=db.Column(db.Text, nullable=True)
    languages=db.Column(db.Text, nullable=True)
    homebrew_id = db.Column(db.Integer, nullable=True)

class Taust(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nimi = db.Column(db.String(20), nullable=False)
    skill_proficiencies = db.Column(db.Text, nullable=False)
    equipment = db.Column(db.Text, nullable=True)
    languages=db.Column(db.Text, nullable=True)
    text = db.Column(db.Text, nullable=True)
    homebrew_id = db.Column(db.Integer, nullable=True)

class Loits(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nimi = db.Column(db.String(20), nullable=False)
    level=db.Column(db.String(20), nullable=True)
    kool=db.Column(db.String(20), nullable=True)
    aeg=db.Column(db.String(20), nullable=True)
    kaugus=db.Column(db.String(20), nullable=True)
    koostisosad=db.Column(db.String(20), nullable=True)
    kestvus=db.Column(db.String(20), nullable=True)
    text = db.Column(db.Text, nullable=True)
    homebrew_id = db.Column(db.Integer, nullable=True)

class Kasutajad(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nimi=db.Column(db.String(20), nullable=False)
    parool=db.Column(db.String(50), nullable=False)
    mail=db.Column(db.String(50), nullable=False)

class Teglased(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    nimi=db.Column(db.String(100), nullable=False)
    taust_id=db.Column(db.Integer, nullable=False, default=0)
    rass_id=db.Column(db.Integer, nullable=False)
    klass_id=db.Column(db.Integer, nullable=False)
    kasutaja_id=db.Column(db.Integer, nullable=False)
    skill_proficiencies = db.Column(db.Text, nullable=False)
    equipment = db.Column(db.Text, nullable=False)
    languages=db.Column(db.Text, nullable=False)
    speed=db.Column(db.Text, nullable=False)
    size=db.Column(db.Text, nullable=False)
    race_feats=db.Column(db.Text, nullable=False)
    feats=db.Column(db.Text, nullable=False)
    class_abilities=db.Column(db.Text, nullable=False)
    max_hit_points = db.Column(db.Integer, nullable=False)
    hit_points=db.Column(db.Integer, nullable=False)
    proficiencies = db.Column(db.Text, nullable=False)
    level=db.Column(db.Integer, nullable=False)
    spells=db.Column(db.Text, nullable=False)
    inspiration=db.Column(db.Boolean, nullable=True)
    proficency_bonus=db.Column(db.String(4), nullable=False)
    ability_scores=db.Column(db.Text, nullable=False)
    ac=db.Column(db.Integer, nullable=False)
    hit_dice=db.Column(db.String(5), nullable=False)
    initiative=db.Column(db.String(4), nullable=False)
    spell_ability=db.Column(db.Text, nullable=False)
    spell_save_dc=db.Column(db.Integer, nullable=False)
    spell_bonus=db.Column(db.String(4), nullable=False)
    info=db.Column(db.Text, nullable=False)

class Homebrew(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    type=db.Column(db.String(20), nullable=False)
    nimi=db.Column(db.String(20), nullable=False)
    kasutaja_id=db.Column(db.Integer, nullable=False)

class Features(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    nimi=db.Column(db.String(20), nullable=False)
    text=db.Column(db.Text, nullable=False)


class Equipment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    type = db.Column(db.String(50), nullable=False)
    category = db.Column(db.String(50), nullable=False)
    description = db.Column(db.Text, nullable=False)
    weight = db.Column(db.Float, nullable=False, default=0.0)
    cost_gp = db.Column(db.Float, nullable=False, default=0.0)
    damage = db.Column(db.String(20), nullable=True)
    properties = db.Column(db.Text, nullable=True)
    ac_bonus = db.Column(db.Integer, nullable=True)
    stealth_disadvantage = db.Column(db.Boolean, nullable=True)
    strength_required = db.Column(db.Integer, nullable=True)
    range = db.Column(db.String(20), nullable=True)
    is_magical = db.Column(db.Boolean, nullable=False, default=False)
    magic_description = db.Column(db.Text, nullable=True)
    rarity = db.Column(db.String(30), nullable=True)
    attunement = db.Column(db.Boolean, nullable=False, default=False)
    charges = db.Column(db.Integer, nullable=True)
    recharge = db.Column(db.String(50), nullable=True)
    source = db.Column(db.String(100), nullable=True)